

package GroupBork;

import java.util.Scanner;

/**
 * The interpreter holds the main method for Bork - here is where the game 
 * interacts with the user and sends out commands according to user input; for
 * this to work there are a few static methods located here to help control 
 * the flow of the game. 
 */
public class Interpreter {

    private static GameState state; // not strictly necessary; GameState is 
                                    // singleton

    public static String USAGE_MSG = 
        "Usage: Interpreter borkFile.bork|saveFile.sav.";

    public static void main(String args[]) {

        String command;
        Scanner commandLine = new Scanner(System.in);
        
        System.out.println("What adventure file would you like to play?");
        System.out.print("> ");
        String filename = commandLine.nextLine();

        try {
            state = GameState.instance();
            
            if (filename.endsWith(".bork")) {
                state.initialize(new Dungeon(filename));
                System.out.println("\nWelcome to " + 
                    state.getDungeon().getName() + "!");
            } else if (filename.endsWith(".sav")) {
                state.restore(filename);
                System.out.println("\nWelcome back to " + 
                    state.getDungeon().getName() + "!");
            } else {
                System.err.println(USAGE_MSG);
                System.exit(2);
            }

            System.out.print("\n" + 
                state.getAdventurersCurrentRoom().describe() + "\n");

            command = promptUser(commandLine);

            while (!command.equals("q")) {
                if(state.getHealth()!=0){

                    System.out.print(
                        CommandFactory.instance().parse(command).execute());

                    command = promptUser(commandLine);
                }
                else
                    System.exit(0);
            }

            System.out.println("Bye!");

        } catch(Exception e) { 
            e.printStackTrace(); 
        }
    }

    private static String promptUser(Scanner commandLine) {

        System.out.print("> ");
        return commandLine.nextLine();
    }
    
    
 /**
 * 
 * This method generates and return a random integer that will be used to trigger
 * an earthquake within the game. 
 * @author Meredith Gregory
 * @return createRandom  A random integer generated by the method 
 * 
 */
    private static int createRandom(){
        
    }

}
